# Site Settings
name: Diogo Carvalho
title: Diogo Carvalho | Software Engineer
email: dmrccarvalho[at]gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog of Diogo Carvalho, a Software Engineer that loves software and technology, but also music, motorcycles, and boardgames.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
show_sidekick: true
menu:
  - title: Blog
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml

# Build settings
#theme: minima
#theme: jekflix
remote_theme: dmrccarvalho/jekflix-template
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - initial_config.yml
  - jekflix_config.yml

# Formspree (https://formspree.io/)
formspree_form_id: mgebgknl

# Disqus (https://disqus.com/)
disqus_username: 

# Social Media Settings
# Remove the item if you don't need it
github_username: dmrccarvalho
facebook_username: 
twitter_username: BossDC
instagram_username: 
linkedin_username: dmrccarvalho
medium_username: 

# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false

# Advanced Settings
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X" # https://www.youtube.com/watch?v=Mtzl4tkVdbI
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-remote-theme